# 1.	create an array with the values from 0 .. 23. And Check its attributes.
   * Then Reshape it as 2*12,3*8, 4*6,; 2*2*6, 2*4*3,3*4*2,.... and check its attributes.


In [12]:
import numpy as np
ar=np.arange(0,24)
print(ar)
print(type(ar))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
<class 'numpy.ndarray'>


* The reshape() function is used to give a new shape to an array without changing its data.
 *Array to be reshaped. The new shape should be compatible with the original shape. 
 * If an integer, then the result will be a 1-D array of that length

In [32]:
ar2=ar.reshape(2,12)
print(" 2X12 matrix form")
print(ar2 ,end="\n\n")
print( " 3X8 matrix formn")
print(ar.reshape(3,8),end="\n\n")
print( " 4X6 matrix formn")
print(ar.reshape(4,6),end="\n\n")
print( " 2X2X6 matrix formn")
print(ar.reshape(2,2,6),end="\n\n")
print( " 2X4X3 matrix formn")
print(ar.reshape(2,4,3),end="\n\n")
print( " 3X4X2 matrix formn")
print(ar.reshape(3,4,2),end="\n\n")

 2X12 matrix form
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]

 3X8 matrix formn
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]

 4X6 matrix formn
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

 2X2X6 matrix formn
[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]]

 2X4X3 matrix formn
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]

 3X4X2 matrix formn
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]



* 2.	Apply a user defined function using vectorize to get the maximum of two arrays
* Example : Array1 =  [5,7,9,8,6,4,5]
* 	     Array2 = [6,3,4,8,9,7,1]
*    Output : [6,7,9,8,9,7,5]



In [36]:
l1=[5,7,9,8,6,4,5]
l2=[6,3,4,8,9,7,1]
array1=np.array(l1)
array2=np.array(l2)
array3=np.maximum(array1,array2)
print("array1",end='\n')
print(array1)
print("array2",end='\n')
print(array2)
print("maximum values from the two arrays",end='\n')
print(array3)


array1
[5 7 9 8 6 4 5]
array2
[6 3 4 8 9 7 1]
maximum values from the two arrays
[6 7 9 8 9 7 5]


* 3.	Write a Numpy program to generate six random integers between 10 and 30

In [39]:
import random
list=random.sample(range(10,30),6)
print(list)

[21, 27, 24, 11, 28, 12]


* 4.	Get all the items between 5 and 10 from Array A.
* A = np.array([2,6,1,9,10,3,27])


In [47]:
a=np.array([2,6,1,9,10,3,27])
array2 = np.take(a,[1,2,3])
print("the values between 5 and 10  from the array:", a)
print(array2)
print("the odd numbers from the array :",a)
for i in a:
    if i%2 !=0:
        print (i,end=" ")
        

the values between 5 and 10  from the array: [ 2  6  1  9 10  3 27]
[6 1 9]
the odd numbers from the array : [ 2  6  1  9 10  3 27]
1 9 3 27 